### ISSUE TITLE
Allow text in command area to be selected and copied to clipboard.

### ISSUE THREAD

**Issue by now0clock** [nikita-yfh/android-adb-tools#1]
It would be really convenient to be able to select text in the bottom command area and copy it to the clipboard. Especially for the output of some commands in fastboot..

![Screenshot_20220806-192610_ADB_ _Fastboot_tools](https://user-images.githubusercontent.com/59995403/183272546-99fd82ca-4122-48d4-a9fb-8e65b86862c7.png)

Also, I noticed an error when tapping "Bootloader Info", under OEM,

**Comment by nikita-yfh** [comment]
Command output are copyable now (https://github.com/nikita-yfh/android-adb-tools/commit/5177cd5e6dfc93cc1f97f2ac49a245c3a42450f6 https://github.com/nikita-yfh/android-adb-tools/commit/16ab375ce0ff20d6727e0b2ffc905bec1a6947b8).
OEM command are vendor-specific and may not work on some devices.

**Comment by now0clock** [comment]
Just wanted to say thanks for this app, I use it often. I have it on a few devices. Works good on a tablet, too..

**Comment by now0clock** [comment]
an open idea, maybe we can get certain OEM commands integrated in there.? maybe a button(s) that just do commands, like:

adb --help
fastboot --help

**Comment by nikita-yfh** [comment]
OEM commands are device-specific, and it is not possible to get a list of them from the Fastboot command line

But i have integrated the most useful commands
