### ISSUE TITLE
Target API

### ISSUE THREAD

**Issue by Universalizer** [nikita-yfh/android-adb-tools#3]
As per Android OS 14 instructions, Target SDK 23.

**Comment by now0clock** [comment]
Yes, I ran into this issue also trying to install on a14::

12-20 08:35:34.128 D/PackageInstallerSession(12508): Marking session 269749758 as failed: INSTALL_FAILED_DEPRECATED_SDK_VERSION: App package must target at least SDK version 23, but found 20

**Comment by nikita-yfh** [comment]
Fixed
